formation/src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TeamRepository::class)
 */
class Team
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $level;

    /**
     * @ORM\OneToMany(targetEntity=Player::class, mappedBy="team")
     */
    private $players;

    /**
     * @ORM\OneToMany(targetEntity=Game::class, mappedBy="teamIn")
     */
    private $gamesIn;

    /**
     * @ORM\OneToMany(targetEntity=Game::class, mappedBy="teamOut")
     */
    private $gamesOut;

    public function __construct()
    {
        $this->players = new ArrayCollection();
        $this->gamesIn = new ArrayCollection();
        $this->gamesOut = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(?string $level): self
    {
        $this->level = $level;

        return $this;
    }

    /**
     * @return Collection|Player[]
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
            $player->setTeam($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        if ($this->players->contains($player)) {
            $this->players->removeElement($player);
            // set the owning side to null (unless already changed)
            if ($player->getTeam() === $this) {
                $player->setTeam(null);
            }
        }

        return $this;
    }

    public function getNbPlayers(): int
    {
        return count($this->players);
    }

    /**
     * @return Collection|Game[]
     */
    public function getGamesIn(): Collection
    {
        return $this->gamesIn;
    }

    public function addGamesIn(Game $gamesIn): self
    {
        if (!$this->gamesIn->contains($gamesIn)) {
            $this->gamesIn[] = $gamesIn;
            $gamesIn->setTeamIn($this);
        }

        return $this;
    }

    public function removeGamesIn(Game $gamesIn): self
    {
        if ($this->gamesIn->contains($gamesIn)) {
            $this->gamesIn->removeElement($gamesIn);
            // set the owning side to null (unless already changed)
            if ($gamesIn->getTeamIn() === $this) {
                $gamesIn->setTeamIn(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGamesOut(): Collection
    {
        return $this->gamesOut;
    }

    public function addGamesOut(Game $gamesOut): self
    {
        if (!$this->gamesOut->contains($gamesOut)) {
            $this->gamesOut[] = $gamesOut;
            $gamesOut->setTeamOut($this);
        }

        return $this;
    }

    public function removeGamesOut(Game $gamesOut): self
    {
        if ($this->gamesOut->contains($gamesOut)) {
            $this->gamesOut->removeElement($gamesOut);
            // set the owning side to null (unless already changed)
            if ($gamesOut->getTeamOut() === $this) {
                $gamesOut->setTeamOut(null);
            }
        }

        return $this;
    }

}

formation/src/Controller/TeamController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class TeamController extends AbstractController
{
    /**
     * @Route("/team", name="team")
     */
    public function index()
    {
        return $this->render('team/index.html.twig', [
            'controller_name' => 'TeamController',
        ]);
    }
}

formation/templates/team/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TeamController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/git/FormationSymfony/formation/src/Controller/TeamController.php'|file_link(0) }}">src/Controller/TeamController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/git/FormationSymfony/formation/templates/team/index.html.twig'|file_link(0) }}">templates/team/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

formation/templates/team/list.html.twig
{% extends "football.html.twig" %}

{% block main %}

<table class="table">
    <thead>
        <th>Nom</th>
        <th>Ville</th>
        <th>Niveau</th>
        <th>Nombre de joueurs</th>
        <th>Actions</th>
    </thead>
    <tbody>
        {% for team in teams %}
            <tr>
                <td>{{ team.name }}</td>
                <td>{{ team.city }}</td>
                <td>{{ team.level }}</td>
                <td>{{ team.nbPlayers }}</td>
                <td>
                    <a href="{{ path('showPlayer', {id: player.id}) }}">Voir</a> |
                    <a href="{{ path('editPlayer', {id: player.id}) }}">Editer</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}